server:
  port: 8080
spring:
  application:
    name: shorturl-api
  profiles:
    active: local

short:
  prefix-url: http://localhost:8080/
  character-list: 0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
  validation-hours: 24
  limited-character-size: 8