server:
  port: 8080
spring:
  application:
    name: shorturl-api
  profiles:
    active: local

short:
  prefix-url: http://localhost:8080/
  character-list: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890
  validation-time: 86400
  limited-character-size: 8